version: "3"
services:
  typesense:
    image: typesense/typesense:0.22.0.rcs28
    entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=abc --enable-cors"
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
  pg:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/
      - ./db/migrations/:/docker-entrypoint-initdb.d/
      - ./local-setup/init.sql:/docker-entrypoint-initdb.d/99999_local_init.sql
volumes:
  pg-data:
    driver: local
  typesense-data:
    driver: local