version: "3"
services:
  pg:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/
  typesense:
    image: typesense/typesense:0.22.0.rcs28
    entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=abc --enable-cors"
    depends_on:
      pg:
        condition: service_healthy
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
  cron:
    build: 
      context: ./
      dockerfile: cron.dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  pg-data:
    driver: local
  typesense-data:
    driver: local